// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFdM64p3piQsszu-HFcQJo0wbtlytAR_4',
    appId: '1:790966046221:web:00580d31848c9a823b4f44',
    messagingSenderId: '790966046221',
    projectId: 'weatherapp-aa00f',
    authDomain: 'weatherapp-aa00f.firebaseapp.com',
    databaseURL: 'https://weatherapp-aa00f-default-rtdb.firebaseio.com',
    storageBucket: 'weatherapp-aa00f.appspot.com',
    measurementId: 'G-PB6XBXWM91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1HiH6_d8XpDPqPd8yKU9ofOFOSK2xfCI',
    appId: '1:790966046221:android:5014cce229cabd7f3b4f44',
    messagingSenderId: '790966046221',
    projectId: 'weatherapp-aa00f',
    databaseURL: 'https://weatherapp-aa00f-default-rtdb.firebaseio.com',
    storageBucket: 'weatherapp-aa00f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQuBfuewvKJmyhL9EoaHS6jrdtS5YZeP4',
    appId: '1:790966046221:ios:593aadb1ad8a83a93b4f44',
    messagingSenderId: '790966046221',
    projectId: 'weatherapp-aa00f',
    databaseURL: 'https://weatherapp-aa00f-default-rtdb.firebaseio.com',
    storageBucket: 'weatherapp-aa00f.appspot.com',
    iosClientId: '790966046221-mpmtg1hjs5vv0t7qaatvd70o50ghq0dr.apps.googleusercontent.com',
    iosBundleId: 'project.flutterAuthorization',
  );
}
